language: r
sudo: required
warnings_are_errors: true
notifications:
  email: false
  slack:
    secure: SyJ/8QQRMMAmE78QKk4SbSp+7nAQm7kyaZaeM5bkvYI/S1MK5BEuDfp1dfC1y1JJ+h6dZC5oi+6+Wkox1SGTGnFHFV4//ih/b2gTtBiqe6S6KemdEFaCs9pIou3lJoVnRNeTVTh88vQYH9W9Qm4hgHQ6wk8+ygOQ0Cp2+aPYhJo=
